### PR TITLE
Attempt to not display revoked keys

### PR DESCRIPTION
**Pull request by cjj20**
This is my attempt to not display revoked keys.

### CODE REVIEW

**Comment by cjj20** [comment]
@fiaxh please review

**Comment by fiaxh** [comment]
Please compile your code and test it before submitting it - this code doesn't even compile.

It also needs lots of cleanup, for example you shouldn't add random commented-out code.

**Comment by cjj20** [comment]
> Please compile your code and test it before submitting it - this code doesn't even compile.
> 
> It also needs lots of cleanup, for example you shouldn't add random commented-out code.

Hi, my apologies and I have compiled but would like to try a new approach. That is using the Gtk.ListStore.remove function along with the gpgme boolean Revoked. I may alternatively grayout the revoked keys.

**Comment by cjj20** [comment]
> Please compile your code and test it before submitting it - this code doesn't even compile.
> 
> It also needs lots of cleanup, for example you shouldn't add random commented-out code.
Improvement made, compiles and hides the revoked keys but only when freshly built. When closed then reopened, revoked keys shows up again. New PR contains changes #1572

**Comment by eerielili** [comment]
hello @cjj20 
>Improvement made, compiles and hides the revoked keys but only when freshly built. When closed then reopened, revoked keys shows up again

I suggest you have a look at https://github.com/dino/dino/pull/1540 and this snippet:
https://github.com/dino/dino/blob/779092c5db10505d8d2b7346a53ec24fa90a348d/plugins/openpgp/src/gpgme_helper.vala#L104-L131

Putting the check for expired or revoked GPG keys in the `get_keylist` function does help not showing them again after restarting Dino.

Kinds regards,
lili

**Comment by fiaxh** [comment]
Closing this PR. It was made as part of a gsoc application and feedback was not addressed.

**Pull request closed without merging**
