### PR TITLE
WIP add automated windows build with appveyor

### PR DESCRIPTION
**Pull request by enko**
The build-process works flawless, but not the resulting binary.

These are problems as outlined in the chat:

* Notifications cause to crash dino. There is an [upstream bug report](https://bugzilla.gnome.org/show_bug.cgi?id=776583)
* `is_24h_format` from `helper.vala` crashes with a segfault.

### CODE REVIEW

**Comment by modInfo** [comment]
```
-- Performing Test COMPILER_SUPPORTS_Wno_unused_label - Success
-- Found PkgConfig: E:/msys2/mingw64/bin/pkg-config.exe (found version "0.29.2")
CMake Error at E:/msys2/mingw64/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GObject (missing: GObject_LIBRARY)
Call Stack (most recent call first):
  E:/msys2/mingw64/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGObject.cmake:17 (find_package_handle_standard_args)
  cmake/FindVala.cmake:49 (find_package)
  CMakeLists.txt:125 (find_package)
```

How to fix `Could NOT find GObject (missing: GObject_LIBRARY)`
I have mingw64/mingw-w64-x86_64-gobject-introspection

**Comment by enko** [comment]
@modInfo if you use the script that I provided it should almost work. There is a problem with gpg, which I had not time yet to dig deeper.

**Comment by alyssarosenzweig** [comment]
https://gitlab.gnome.org/GNOME/glib/issues/1234 Upstream issue tracking Windows notifications ... looks like there's some code floating around unmerged, but the crash should be fixed by now.

**Comment by fiaxh** [comment]
Closing this WIP PR due to lack of progress.

**Pull request closed without merging**
