### PR TITLE
message_item: add encryption_image tooltips

### PR DESCRIPTION
**Pull request by astro**
Thank you for creating dino!

### CODE REVIEW

**Comment by astro** [comment]
## Preview
Screenshot

**Comment by NicoHood** [comment]
How about "OMEMO encrypted"?

**Comment by astro** [comment]
@NicoHood whatever floats your boat!

**Comment by NicoHood** [comment]
I thought of this while reading the string:
https://elementary.io/docs/human-interface-guidelines#get-to-the-bottom-line

> Put the most important information at the beginning of your text. If the user stops reading, they'll still have what they need in mind.

    Bad: Your network connection might be down because Lingo could not find any definitions. Check it and try again.
    Better: No definition found. Check your network connection and try again.

**Comment by astro** [comment]
Insightful, thank you! Reworded and rebased.

**Comment by NicoHood** [comment]
@astro Can you please add the date to the tooltip? https://github.com/dino/dino/issues/78

**Comment by astro** [comment]
separate PR

**Comment by astro** [comment]
I really need help implementing this additional wish.

**Comment by astro** [comment]
Rebased to current `master`

**Comment by fiaxh** [comment]
Thank you for doing the pull request. Except for the `Encryption` enum, the `main` package does not know about the different encryptions. The complete code is in the omemo / openpgp plugins. I'd like the tooltip text to also to be generated by the plugins, however the plugin API needed for that does not yet exist.

> "Read at date, time".

The time at which a message was read by the recipient is currently not being saved and I don't really see a need for it.

**Pull request closed without merging**
