### PR TITLE
Add more info on build deps

### PR DESCRIPTION
**Pull request by licaon-kter**
As needed on Lubuntu 17.10 at least.

### CODE REVIEW

**Comment by fiaxh** [comment]
Duplicate of #56

**Comment by licaon-kter** [comment]
The current info is not enough.

Please merge this, or edit it yourself in some other format, the fact that I needed to re-run configure a dozen times and hunt for the matching packages names in Synaptic makes this necessary. :(

**Comment by d9h20f** [comment]
Distribution packages for Ubuntu are available: https://github.com/dino/dino/wiki/Distribution-Packages

Generally, if someone wants to manually compile something for which a package for their distro is already available, they already know how to set up a build environment.

**Comment by licaon-kter** [comment]
That's true to a point, my problem is that the info in just partial, either the user `already knows how to` and this is not needed at all, or provide complete info. Now it's: `you kinda need these libs and see whatever error ninja spits out`

**Pull request closed without merging**
