### PR TITLE
Add Appimage support and build workflow; fixes #278

### LINKED ISSUE #278: Feature Request: Appimage Release
I do not know how difficult it would be to release an appimage but the reason I ask is that an AppImage might allow for people to use dino on certain distros that do not have a native release since they lack the newer libraries required for Vala (i.e. Ubuntu 16.04). Right now dino is built on the OpenSUSE Open Build System which allows for building to AppImages, so hopefully this is not a difficult task to make one for dino. If this is not possible I would like to know why, and what the limitations of an AppImage are for this particular program.

### PR DESCRIPTION
**Pull request by zocker-160**
This is a draft, since I am still having issues when running on Debian 10 or Manjaro systems and I am not sure how to solve it.

Maybe someone has an idea, what is causing this error. It works fine on Ubuntu 20.04.

this is the error I am getting:
```
$ ./dino-0.2.0-x86_64.AppImage 

** (dino:2179): CRITICAL **: 15:33:33.473: file /home/runner/work/dino/dino/main/src/ui/main_window.vala: line 68: uncaught error: Unrecognized image file format (gdk-pixbuf-error-quark, 3)

(dino:2179): Gtk-WARNING **: 15:33:33.551: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Abgebrochen
```

This would solve #437, #941 and #278

### CODE REVIEW

**Comment by githuberyt** [comment]
Agreed I have issues with dino on debian 10 providing flatpak support or appimage would be great

**Comment by paskalito** [comment]
this Appimage, https://github.com/dino/dino/actions/runs/759133261 just works for me on debian.
Is there a way to get an appimage generated for the nightly build?

**Comment by zocker-160** [comment]
@paskalito thank you for this feedback, are you running Debian buster?
On Manjaro this problem still persists, but I am not really sure how big of a problem that is, since Manjaro users have dino in their repos anyway.

>  Is there a way to get an appimage generated for the nightly build?
Yes but only if this PR gets merged.

**Comment by paskalito** [comment]
@zocker-160 thank you for your efforts!
yes, i'm on Debian 10/buster.

Unfortunately i do not understand most of how appimages get generated. but is there a way i can somehow get any one nightly version ( also just for me) ?

**Comment by zocker-160** [comment]
@paskalito 
> also, who decides when and how if this PR gets merged?
That depends on if the devs of dino think that it is ok that the build currently does not work on Manjaro or not.

Regarding nightly builds, I need to check what I can do, but it should be possible to set a nightly build workflow up.

**Comment by LAGonauta** [comment]
AFAIK those pixbuf libraries are loaded in runtime. I had to manually copy them to the package for the Windows version, maybe you have to do the equivalent to the AppImage?
For Windows:
```
(...)
   mkdir -p ./lib/gdk-pixbuf-2.0/ && cp -r /mingw64/lib/gdk-pixbuf-2.0 ./lib/ && \
   mkdir -p ./lib/gio/ && cp -r /mingw64/lib/gio ./lib/ && \
(...)
```

**Comment by zocker-160** [comment]
I gave up on this, Appimage is way too cumbersome to package. If anyone wants to work further on this / take over, feel free to fork my Appimage branch  [here](https://github.com/zocker-160/dino/tree/Appimage) (I will not delete it).

I personally moved over to MPR if anyone is interested to use those packages instead: [dino](https://mpr.hunterwittenborn.com/packages/dino/) and [dino-git](https://mpr.hunterwittenborn.com/packages/dino-git/).

**Comment by mj162** [comment]
Thank you for trying and obviously regret that you found it challenging and wonder whether you reached-out to the AppImage people before giving-up on it.  There are nightly builds for various AppImages.  One I refer to frequently is for [Waterfox](https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/AppImage/).

**Comment by zocker-160** [comment]
> Thank you for trying and obviously regret that you found it challenging and wonder whether you reached-out to the AppImage people before giving-up on it. There are nightly builds for various AppImages. One I refer to frequently is for [Waterfox](https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/AppImage/).

@mj162 
The main issue with Appimage is not that the build process itself is bad (the yml approach works fine), it is that Appimages are not truly portable and still depend on system packages (see https://github.com/AppImage/pkg2appimage/issues/378), which is the reason for the error I had with dino, because it is expecting some GTK icons to be present on the system.

This also shows your linked Waterfox builder, where they have to offer multiple Appimages.

Furthermore Arch based distros are officially not supported, see the official statement: https://github.com/AppImage/pkg2appimage/issues/378#issuecomment-501562070

As long as Appimages are not truly portable, IMO you can use a DEB package just as well without the size penalty.

**Comment by mj162** [comment]
Hi @zocker-160, I don't pretend to fully understand, but thank you for taking the time to show me the issues being faced.  I understand a little better.

In principle, I am for portable apps and am supremely unconcerned by size penalty so long as some application-centric updating doesn't result in the accumulation of multiple copies of several-hundred-megabyte apps in local home directories...

I hold no candle for AppImage, but in the portable app space, it's the least inconvenient of the portables in my environment.

Today, Cisco WebEx&copy;, Microsoft Teams&copy;, Verizon BlueJeans&copy; and Zoom&copy; desktop clients appear to be distributed as statically-linked binaries inside DEBs and RPMs that can be dearchived just fine and run off removable media or shares without the privilege or need to invoke the distro's package manager.

So, as I see it, AppImage is the least worst portable which is why I advocated for it when Cisco asked "[*what flavours [of Linux] will be supported*][1]" and folk piled-in, [Uncle Tom Cobley and all][2], with a very long list.  Sometimes we would do well to remember that Linux is a minority so expecting developers to *slice and dice* into distro-specific downloads is an unreasonable ask when they just have to put out one for Microsoft Windows&copy; and one for Apple MacOS&copy;.  Ultimately I can lapse into agnosticism over which *portable* community and commercial developers adopt, but standardisation is now long overdue.

I appreciate the icon grief:  Even though I have them in one of my `XDG_DATA_DIRS/icons` I'm plagued by my launcher dock seemingly not following the [standard][3] and substituting default application icons.  That said; [Waterfox][4] AppImage's icon (and the icons from other AppImages such as [LibreOffice][5]) are displayed without problem. Apparently, "An AppImage also contains resources like strings, [icons][6], pictures, documentation, etc."

[1]: <https://ciscocollabcustomer.ideas.aha.io/ideas/WXCUST-I-61>
[2]: <https://idioms.thefreedictionary.com/Uncle+Tom+Cobley+and+all>
[3]: <https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html>
[4]: <https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/AppImage/>
[5]: <https://www.libreoffice.org/download/appimage/>
[6]: <https://www.reddit.com/r/linux/comments/5jqnca>

**Comment by zocker-160** [comment]
I actually fully support your view @mj162, Appimage is the best portable format Linux has right now, size is secondary and if you create a truly portable Appimage (as I was talking about earlier), then it will just work on any distribution.

While it is possible to create such an Appimage today, it is painful and time consuming, especially if you want to do it properly.
You still need to do testing on as many distros as possible and add distro specific fixes to make it work. You simply cannot expect a company to do this, it has to be as easy as possible for maximum adoption.

On top of that there are many Appimages out there which will only work on certain distributions, which defeats the entire point of them imho.

The Dino appimage I build right now, does also work for "most" ppl, but for me that is not a proper solution.

Cisco WebEx© is actually not a great example for portability, because it comes with a huge list of system dependencies
```
binutils, xdg-utils, libgl1-mesa-glx, libnss3, libnspr4, libcups2, upower, libnotify4, libsecret-1-0, libwayland-client0, libatk1.0-0, libatk-bridge2.0-0, libgbm1, libpango-1.0-0, libpangocairo-1.0-0, libatspi2.0-0, libgssapi-krb5-2, libasound2, libudev1, libpulse0, libxcb-randr0, libxcb-xfixes0, libxcb-xinerama0, libxcb-render-util0, libxcb-keysyms1, libxcb-image0, libxcb-icccm4, libxkbcommon-x11-0
```
which are not part of the DEB.

If we want actual portability, then _everything_ needs to be bundled, just like MacOS does it with dmg packages.

**Comment by mj162** [comment]
@zocker-160, Thank you.  I've really enjoyed dialogue with you and have learned from you.

Your remarks regarding AppImages that don't in fact work on a variety of distros (absence of sandboxing support in Arch apart) is so so true.  On the home page of [Apprepo.de](https://apprepo.de/) there's a long bullet list of builds their apps *won't* work on, and Ubuntu 20.04 on the "works on" list implies they won't work on Ubuntu 16.04LTS (on which HP ThinPro 7.1 is based) and 18.04LTS (on which HP ThinPro 7.2 is based).

I applaud your preference to do portable apps *properly* or not at all, and I completely concur with your remarks that:
> "Cisco WebEx&copy; is actually not a great example for portability, because it comes with a huge list of dependencies".

I'm seeing just that.  Cisco WebEx&copy; won't work on HP ThinPro 7.1 (Ubuntu 16.04LTS-based), but Verizon, Zoom and, darn it, even Microsoft, manage to get their respective Linux desktop collaboration apps to be upwardly compatible of Ubuntu 16.04.

I ended by asking for standardisation.  Chastened by that adage from Aesop's Fables that one should "*be careful for what you wish for, lest it become true*",  and not to start or add fuel to any mainstream or alternative conspiracy theories, it's clear that if/when there is market consolidation in commercial Linux distros, that would no-doubt bring-about that much-needed portable apps standardisation.

**Comment by alexanderadam** [comment]
I'm not quite sure whether anything changed in the meantime [but @fiaxh once wrote](https://github.com/dino/dino/pull/121#issuecomment-321332304):

> [We would like to not have any package build system specific configurations in our repository.](https://github.com/dino/dino/pull/121#issuecomment-321332304)

So I guess this wouldn't happen anyway. :disappointed:

**Comment by mj162** [comment]
Happy new year!

Too bad.  In 2023 the best way to get your package the widest ordinary user audience is AppImages or static binaries (like Zoom, just for one example).

For those that don't make it so easy, the majority of users will just sigh and move-on.  TBH, I've genuinely actually forgotten what Dino is and just go-on enjoying using the AppImages like Libreoffice and statics like Zoom, updating as frequent releases come-by safe knowing they will still work because they're self-contained.

All the best.

**Comment by paskalito** [comment]
@zocker-160 unfortunately i cannot download the Appimage [here](https://github.com/zocker-160/dino/actions/runs/1289037225) anymore, and apparently my local copy is gone too.
Do you have still one laying around, you could upload somewhere or get it built/downloadable again?

**Comment by zocker-160** [comment]
@paskalito oh I did not know someone was still using the build from there. I will revive the build workflow tomorrow.

**Comment by zocker-160** [comment]
@paskalito there you go, I rebased on 0.2.2 and triggered a rebuild, it should be available in a few minutes:
https://github.com/zocker-160/dino/actions/runs/1704284561

**Comment by paskalito** [comment]
@zocker-160 WOW, thanks a million times! It works Perfectly, this time i did a proper Backup of it, so all the ppl on Linux can use multidevice XMPP with their Computers! (also in the Future)

**Comment by grugel-maintro** [comment]
Appimage does not work anymore

```bash

** (dino:11819): CRITICAL **: 19:07:47.257: file /home/runner/work/dino/dino/main/src/ui/main_window.vala: line 68: uncaught error: Unrecognized image file format (gdk-pixbuf-error-quark, 3)

(dino:11819): Gtk-WARNING **: 19:07:47.520: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted

```

**Comment by mj162** [comment]
It's frustrating when that happens.

Haven't actually been using dino or XMPP in general.

Is there an xUbuntu 16.04 binary still around?  Ubuntu 16.04
being a little to old to be included in the binaries found here:

https://software.opensuse.org/download.html?project=network:messaging:xmpp:dino&pac
kage=dino

Happy Christmas


----- Original Message -----
Date: Tue, 27 Dec 2022 11:15:12 -0800
From: grugel-maintro ***@***.***>
To: dino/dino ***@***.***>
Cc: mj162 ***@***.***>, Mention 
***@***.***>
Subject: Re: [dino/dino] Add Appimage support and build workflow (#1033)

Appimage does not work anymore

```bash

** (dino:11819): CRITICAL **: 19:07:47.257: file 
/home/runner/work/dino/dino/main/src/ui/main_window.vala: line 68: uncaught error: 
Unrecognized image file format (gdk-pixbuf-error-quark, 3)

(dino:11819): Gtk-WARNING **: 19:07:47.520: Could not load a pixbuf from icon 
theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion 
failed (error == NULL): Failed to load 
/org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file 
format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: 
assertion failed (error == NULL): Failed to load 
/org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file 
format (gdk-pixbuf-error-quark, 3)
Aborted

```

**Comment by zocker-160** [comment]
Yeah this is exactly why I abandoned the Appimage, it is unreliable and breaks randomly for no reason.

**Comment by mj162** [comment]
Directing comments like that to me will likely not reach someone
that can respond to your issue with AppImage and/or help you.

https://github.com/srevinsaju/Brave-AppImage/

Seems to manage to publish nightly AppImage builds of a chrome
based web browser

https://www.libreoffice.org/download/appimage/

Seems to manage to publish frequent AppImage builds of an Open
Office based office app

Both, and many more, still run on EOL Ubuntu 16.04 for example.


----- Original Message -----
Date: Thu, 29 Dec 2022 03:58:06 -0800
From: zocker-160 ***@***.***>
To: dino/dino ***@***.***>
Cc: mj162 ***@***.***>, Mention 
***@***.***>
Subject: Re: [dino/dino] Add Appimage support and build workflow (#1033)

Yeah this is exactly why I abandoned the Appimage, it is unreliable and breaks 
randomly for no reason.

**Pull request closed without merging**
