### PR TITLE
Trayicon

### PR DESCRIPTION
**Pull request by wkg**
I know Gtk.StatusIcon is deprecated, but this is really needed of many people who do not using gnome3...
#98

### CODE REVIEW

**Comment by fiaxh** [comment]
As mar-v-in mentioned in the respective issue https://github.com/dino/dino/issues/98#issuecomment-522249766, we would like to add tray icon support by directly implementing the [StatusNotifierItem](https://freedesktop.org/wiki/Specifications/StatusNotifierItem/) DBus interface.

I'll be happy to merge a PR that implements tray icons that way. Implementing DBus interfaces is rather doable in Vala, we already do it in [three instances](https://github.com/dino/dino/tree/master/libdino/src/dbus). If you have any questions about it, please feel invited to ask us.

**Comment by Junker** [comment]
what do you think about using this lib: https://github.com/SkyMaverick/statusnotifier ?
It has vapi for vala, can easily integrate to Dino.

**Comment by emildekeyser** [comment]
Hey wkg are you still working on this ?

**Comment by wkg** [comment]
> Hey wkg are you still working on this ?

I try, but have no time

**Comment by emildekeyser** [comment]
If you like I can take over, I have some time right now to work on some features that I desire. Have you already written some SNI/dbus code or not ?

**Comment by wkg** [comment]
> If you like I can take over, I have some time right now to work on some features that I desire. Have you already written some SNI/dbus code or not ?

It would be great. No, I haven't done anything yet

**Pull request closed without merging**
