### PR TITLE
make symbolic icon height width same for flathub

### PR DESCRIPTION
**Pull request by Aman9das**
Issue here: https://buildbot.flathub.org/#/builders/21/builds/7539

> error: /srv/buildbot/worker/build-aarch64-5/build/builddir/export/share/icons/hicolor/symbolic/apps/im.dino.Dino-symbolic.svg is not a valid icon: Expected a square icon but got: 300x304

### CODE REVIEW

**Comment by fiaxh** [comment]
Thanks for your PR. This is done on master in e554f90ff92d6818ca399983e47d54b89352d5a2.

**Comment by Aman9das** [comment]
Thanks!

Also I just wanted to confirm, whether you have access to the flathub https://github.com/flathub/im.dino.Dino repository, the packaging does not seem to have any major issue remaining.

**Comment by fiaxh** [comment]
@Aman9das I have access, yes. As far as I can tell there is at least one issue remaining where Dino always crashes on video calls https://github.com/flathub/im.dino.Dino/issues/7 (which I can reproduce). According to the person that reported the issue, that should be fixed with the next gnome platform version. After that, we can test whether everything is working. If everything is working, I guess it's ready to go to flathub stable :+1:

**Comment by Aman9das** [comment]
I have updated the dino flatpak to the new gnome SDK, hopefully the crash is fixed (I cant really test myself)

**Pull request closed without merging**
