### PR TITLE
Added more public servers

### PR DESCRIPTION
**Pull request by dimethyltriptamine**
In this commit I've added more public XMPP servers to the account creation dialog:
* dismail.de
* intux.de
* parloteo.es

### CODE REVIEW

**Comment by licaon-kter** [comment]
Why those?

**Comment by qorg11** [comment]
Picked randomly from compliance.conversations.im and they have a good privacy policy

**Comment by mimi89999** [comment]
Could you please add them to https://invent.kde.org/melvo/xmpp-providers ?

**Comment by fiaxh** [comment]
I feel that picking servers for this list is a rather difficult thing.
Of course we ideally want servers that support all the XMPP features that Dino supports. They should have a reasonable privacy policy. They should have a good record of uptime. Those three things can easily be checked.

However, there are also aspects that are more difficult to estimate: We want servers that won't go offline anytime soon. We want servers that won't close registration anytime soon (We can't update the Dino version in Debian Stable / Ubuntu, and they stay around for more than two years). We want servers that are maintained by multiple people.

For example, from your PR dismail.de closed registrations by now.

We'll need a better solution for our server suggestions. Until we found one, I don't see us adding servers from PRs. If you have a strong case for one specific server, please feel free to mention it in our XMPP channel.

**Pull request closed without merging**
