### PR TITLE
Small i18n fixes

### PR DESCRIPTION
**Pull request by linkmauve**
Make the original strings better, and add a translator comment.

### CODE REVIEW

**Comment by NicoHood** [comment]
What does it improve except that those are special chars that nobody can simply type?

**Comment by d9h02f** [comment]
The single-glyph ellipsis is specified by GNOME guidelines, you can easily type it with Alt Gr + .

**Comment by linkmauve** [comment]
Hi, any news on this PR?

**Comment by fiaxh** [comment]
Merged, thanks!

**Pull request merged**
