### PR TITLE
Improvements to the OMEMO plugin - trust management, MUCs, and bug fixes

### PR DESCRIPTION
**Pull request by sdhand**
This PR is the final result of the work done for my Google Summer of Code 2018 project. ["Improving OMEMO support in dino: Blind trust before verification and encrypted groupchats"](https://summerofcode.withgoogle.com/projects/#5347422025285632).
Note for GSoC: The final commit made during the program was https://github.com/sdhand/dino/commit/65a12021bc7abbf5ddea068ffe9b4715cfc34f0b: "Solve a few compiler warnings"

### Work Description
- Trust Management
    - UI that allows the user to choose to accept or reject device keys belonging to contacts
    - New keys are trusted by default, this may be manually turned off or is turned off automatically upon choosing to verify one of the contact's key's fingerprints
    - Option to display a QR code for the own fingerprint to allow for easy verification. This uses the same format as the popular android client conversations.
- OMEMO in MUCs
    - It is now possible to send OMEMO encrypted messages in multi-user chats (MUCs)
    - This is only implemented in members only, non-anonymous chats (as information needed to build OMEMO sessions is stored in PEP nodes for each user)
- Bug fixes
    - Various bugs with initial OMEMO session creation have been fixed
    - This (hopefully) fixes issues such as #112, #128, #206, and #243
    - Obviously necessary to have users try out and test these fixes 

### Future Work
- QR Code Based Verification
    - Eliminates the need for users to manually compare and verify fingerprints for keys
    - Would require creating a vapi for a library such as [zbar](http://zbar.sourceforge.net/)
- Better marking of messages from devices with rejected or unknown keys
    - Currently the message body is altered to signify this - whilst suitable as a temporary measure this is not ideal
    - Should hide or not display messages encrypted with rejected keys and use some symbol or text above the message to mark those using unknown keys
    - Likely depends on the work of another GSoC student working on Dino

### CODE REVIEW

**Comment by stevenroose** [comment]
@sdhand Could this be rebased? I'd be very interested for @fiaxh to be able to review this..

**Comment by sdhand** [comment]
@stevenroose the PR has been reviewed quite extensively but requires additional work. I am fairly busy at the minute, hence the delay on it getting merged. Apologies for this.

**Comment by stevenroose** [comment]
@fiaxh thoughts??

**Comment by Echolon** [comment]
@sdhand have you check the conflicts?

**Comment by wilhelmy** [comment]
I think the longer this PR stays open, the more conflicts it will accumulate. It would be really sad to see this effort go to waste since the lack of proper OMEMO support in all major clients is ruining XMPP for me at the moment. Thank you for trying to change that.

**Comment by wilhelmy** [comment]
I wasn't trying to increase pressure (I'm in no position to demand anything from anyone here), but I felt the PR needs a friendly bump. I know  how hard it can be to push things further when you're already busy.

Just to clarify, by remaining work you mean the things listed in "Future work", or tasks resulting from the code review? What actually remains to be done? Can other people help somehow?

**Comment by vanitasvitae** [comment]
As a fellow GSoC student, I'd recommend you to divide your work into small pieces. Make a new PR for every small feature and improvement. That way you can slowly catch up while having your code merged continuously without being stale for too long :)

**Comment by sdhand** [comment]
As for remaining work, the main task left to do is adding a table that stores the identity key for each message, and using the work of the other GSoC student hide messages from untrusted keys.

**Comment by stevenroose** [comment]
@sdhand about that last one, is that hiding for explicitly untrusted? Or also not-yet-trusted keys?

**Comment by sdhand** [comment]
@stevenroose for now we've opted to just go with my existing solution of marking messages from unknown keys as wontsend (they display, but with a large warning symbol above)

**Comment by vanitasvitae** [comment]
:tada:

**Comment by NicoHood** [comment]
Does this also implement support for encrypted files, such as images? If not, this work was done here: https://github.com/dino/dino/pull/339

**Comment by stevenroose** [comment]
> As for remaining work, the main task left to do is adding a table that stores the identity key for each message, and using the work of the other GSoC student hide messages from untrusted keys.

I'm a bit confused; has this work actually been done? Or did we loose patience and merged as-is?

**Comment by vanitasvitae** [comment]
Just tested the new changes. Veeery nice work :) I bet I'm not the only one who'd love to see a blog post about the changes on planet.jabber.org ;)

**Comment by wilhelmy** [comment]
Best news this week!

Only thing I noticed so far is that compiling fails if qrencode.h is missing.

git master runs very stable. Great work, thanks a lot.

**Pull request merged**
