### PR TITLE
Fix " Dino does not add own account to roster" (#696)

### LINKED ISSUE #696: Dino does not add own account to roster
Source: Git AUR

1) Click on "+"
2) Choose your account with JID A
3) Enter JID A into the JID field for your new contact
4) Give it a nickname
5) Press "add"

Result: The window closes and the contact is not in the list. Besides that, there's no warning or something else. 

Works if I choose a different account, though.

### PR DESCRIPTION
**Pull request by eerielili**
should close #696

### CODE REVIEW

**Comment by tmolitor-stud-tu** [comment]
@mar-v-in will these or other prs ever be merged? if not I think I'll switch the client to something actively developed.

**Comment by tmolitor-stud-tu** [comment]
Well, I took that PR just as an example, there are plenty of other PRs not merged, not commented or reviewed but not merged nevertheless.

Small commits fixing some small bugs isn't exactly the metric I'd use for an "active project". Especially if such a huge list of PRs is open that fix several bugs and even implement new features.
And you can be glad that that much people are interested in providing pull requests rather than letting you do all the work on your own. Over at Monal we rarely get PRs at all!

We talked already at C3: having more and more xmpp clients more or less abandoned does hurt the reputation of xmpp, especially at the current stage where it isn't that widespread we all wish it was.
Seeing Dino become such a more or less abandoned client, too, merely proofs the point I made when we talked ad C3. That's sad!

**Comment by eerielili** [comment]
@fiaxh 
>the question is more if we want this to be done like this. [...] but how or if we want to do it in Dino is a UX decision that wasn't made yet

Thanks for the feedback.
FYI, I have #1481 for an implementation in the UI if interested.
image

image
(i did remove the shortcut)

@tmolitor-stud-tu You might want to have a look at https://github.com/mxlgv/dino (Dino+)

**Comment by licaon-kter** [comment]
@eerielili so I have 7 logged accounts, there's a popup afterwards so I choose which one?

**Comment by eerielili** [comment]
@licaon-kter Done. I reused the "Start Conversation" window code with some tweaks.
If you have one account enabled, a new chat will yourself will pop on the chat list.
If you have more than one, this will open:
image

I'll push my change in #1481.

**Comment by eerielili** [comment]
Moved the logic to https://github.com/dino/dino/pull/1481.

**Comment by tmolitor-stud-tu** [comment]
@eerielili Yes, I already saw Dino+ and also Dino++ (https://codeberg.org/Taba/dino-plus-plus)
Currently I'm running Dino++

**Pull request closed without merging**
