### PR TITLE
OMEMO device ID access model changed to open

### LINKED ISSUE #1139: OMEMO device ID PEP node left with default access model.
The OMEMO device ID PEP node is not configured with `access_model=open` like the bundle node. It should be, or it may cause trouble with private groups lacking complete mutual presence subscriptions among all participants, and for clients that use `publish-options` to enforce the access model setting without handling a failed publish.

### PR DESCRIPTION
**Pull request by pravi**
Fixes #1139

### CODE REVIEW

**Comment by pravi** [comment]
This result in,

```
/<<PKGBUILDDIR>>/plugins/omemo/src/protocol/stream_module.vala:81.113-81.145: error: Argument 6: Cannot convert from `unowned string' to `unowned Xmpp.Xep.Pubsub.PublishOptions?'
   81 |                 stream.get_module(Pubsub.Module.IDENTITY).publish.begin(stream, jid, NODE_DEVICELIST, id, node, Xmpp.Xep.Pubsub.ACCESS_MODEL_OPEN);
      |                                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  

```

**Comment by pravi** [comment]
Thanks to Abraham Raji, this build error is fixed now.

**Comment by fiaxh** [comment]
Thanks for your PR.

This was done in 95fefaff51e5506d3f0e5fe8bced14aeb3fbe037, in a slightly more fault-tolerant way.

**Comment by pravi** [comment]
@fiaxh thanks!

**Pull request closed without merging**
