### PR TITLE
Support incoming encrypted HTTP upload file transfers with aesgcm URI scheme

### PR DESCRIPTION
**Pull request by ThibG**
Many XMPP clients supporting OMEMO use a non-standard URI scheme for end-to-end encrypted files through HTTP upload.
This pull request implements receiving such file transfers (outgoing file transfers are still *unencrypted* even in an OMEMO-enabled conversation).
I had to add new interfaces, since the HTTP upload and OMEMO plugins are independent. I am not too sure about those changes, but I have not found a better way.

### CODE REVIEW

**Comment by Mic92** [comment]
Conversation also seems to now use https links without the special protocol, but with an anchor tag for they key. Is this covered here as well?

**Comment by stevenroose** [comment]
Is there any progress on getting this feature accepted? Seems like there was no feedback whatsoever..

**Comment by NicoHood** [comment]
I tried to resolve the conflicts in this brach/commit here:
https://github.com/NicoHood/dino/commit/02cc93a4905fd485f91fed4e4ce1652227a71289

But it is not working as expected. Nothing changed.

**Comment by selurvedu** [comment]
This may be helpful for making use of `aesgcm://` URIs until this feature is implemented in Dino: https://github.com/dino/dino/issues/419#issuecomment-437841957

**Comment by fiaxh** [comment]
Thanks for doing this, I'm sure some people complied this PR to get AES-GCM links working. The PR wasn't merged as we thought we needed a more general approach without forcing AES-GCM links to work based on the http-files plugin. I used parts of your decryption code to implement AES-GCM links as another `FileProvider` in 01360a7.

AES-GCM links file up- and download is now implemented on master.

**Comment by NicoHood** [comment]
The picture decryption does not work for older messages, where dino did not support the decryption.

**Comment by NicoHood** [comment]
Version dino-git-r385.542744a-1 now works. But older encrypted pictures are lost/not shown.

**Comment by NicoHood** [comment]
Another issue:
If you are in chat B but person A sends you a picture there is a text "image received". on the first receiving this text was bold(unread), and stayed bold until i wrote some text. On the second try it was not even bold. There must be something wrong with the read flag.

**Comment by licaon-kter** [comment]
@NicoHood known issue

**Pull request closed without merging**
