### PR TITLE
ptbr translations update

### PR DESCRIPTION
**Pull request by paulocanedo**

### CODE REVIEW

**Comment by licaon-kter** [comment]
Is the translation site that bad?

**Comment by paulocanedo** [comment]
@licaon-kter not bad, just incomplete as you can see at Files changed

**Comment by licaon-kter** [comment]
The translation **site**...

https://hosted.weblate.org/projects/dino/

**Comment by paulocanedo** [comment]
I didn't know about this site...

**Comment by licaon-kter** [comment]
Wiki -> [Translations](https://github.com/dino/dino/wiki/Translations)

**Comment by d9h20f** [comment]
It's no problem if you want to use pull requests to update the translations, but it's easier to keep of changes with Weblate.

**Comment by paulocanedo** [comment]
@d9h20f its ok, I already sent translations to weblate, btw there are 6 days since I uploaded translation file and still not replicated to github project, is that a problem?

**Pull request closed without merging**
