### PR TITLE
Upload files on drag and drop (fixes #175)

### LINKED ISSUE #175: drag and drop for HTTP file upload
A nice convenience feature I suggest is the possibility to upload/ send files just drag-n-dropped into the conversation window.
The GTK file picker is (at least on my KDE system) often a bit inconvenient, as it doesn't allow good previews of multiple images.

### PR DESCRIPTION
**Pull request by ThibG**
Local files dragged to a chat window will get uploaded.

The code probably needs some refactoring, but I'm not too sure how.

### CODE REVIEW

**Comment by stevenroose** [comment]
Does this still work? Could you rebase?

**Comment by ThibG** [comment]
Rebased. This still works, albeit not when dragging to the text input. I'm not sure that worked before the rebase. (The reason that doesn't work is that I seem to need to reimplement every drag'n'drop event if I am to add image drag'n'drop support?)

**Comment by makmm** [comment]
why is this not getting merged? :(

**Comment by stevenroose** [comment]
Does this also add image paste support?

**Comment by fiaxh** [comment]
Thanks, I merged this in f5e0ecafae87c73d4d2959976849306011b65d85 and a7e92960a3f4d31cfb2fbe2e3ba4941cf3b8faf2. Also, I changed the drop area slightly so that it now includes the conversation content area as well as the text input area below (28c44380ba89e51c5aeac01ca9549633fbeb7e11).

@ThibG Apologies for putting of to review and merge this (good) PR for so long, I'll try to improve that.

**Pull request closed without merging**
