### PR TITLE
Show a full timestamp in the relative time tooltip

### LINKED ISSUE #78: [FR] Mousover Time should give the full date
Minor Feature.
"7 mins ago" is in general a good term. However if you want the exact time without calculating, or even in seconds I personally expected that a mouseover would show a tooltip with the full date + time. Or at least only the time, but with seconds.

### PR DESCRIPTION
**Pull request by hrxi**
Fixes #78.

### CODE REVIEW

**Comment by NicoHood** [comment]
Cool! Can you please post a screenshot about that?

**Comment by hrxi** [comment]
I don't have a test account right now, so I'm only showing the timestamp and the tooltip and not the whole window:

timestamp

**Comment by NicoHood** [comment]
Nice. I dont know if the black background is theme dependent. But the feature itself looks nice, exactly what I want :)

**Comment by hrxi** [comment]
It's probably theme-dependent – if you look into the code, you'll see that I'm simply setting the `tooltip` property, i.e. I'm not modifying the style of the tooltip at all.

**Comment by fiaxh** [comment]
This is problematic because messages are merged. Currently although the time of the first message is used for the headline, the time also (mostly) applies to merged messages, as the time-info does not attempt to be precise. However if done as in this PR, you would only accurately show the time of the first message. That would be confusing and only of limited usability.

**Comment by NicoHood** [comment]
maybe the tooltip should show the latest message then? i think the main point is to get an absolute date/time, not a relative one to the current time (3mins ago)

**Comment by hrxi** [comment]
I think the timestamps were made more precise since the PR was opened. See also @fiaxh's reasoning.

**Pull request closed without merging**
