### PR TITLE
Fix for jabberd XMPP server 'infinity' http upload file size announce

### PR DESCRIPTION
**Pull request by eerielili**
should fix https://github.com/dino/dino/issues/1222

### CODE REVIEW

**Comment by fiaxh** [comment]
Did you test this with an ejabberd server that has the maximum size set to infinity? Or do you have an example stanza? I quickly searched through the source code of Conversations and Gajim and didn't find the string "infinity" in either of them, hence I'm wondering if this is really what is sent on the wire.

**Comment by eerielili** [comment]
@fiaxh No, I naively assumed it sent back the string "infinity" when reading the issue.
I did test things out after your comment by setting up a simple ejabberd instance and putting some `stderr.printf` in the `extract_max_file_size` function like so:
```vala
                if (var_attr == "max-file-size") {    
                    StanzaNode value_node = node.get_subnode("value", "jabber:x:data");    
                    max_file_size_str = value_node.get_string_content();    
                    stderr.printf("\nReported file size limit is %s bytes.\n\n", max_file_size_str);    
                    break;    
                }    
```

When setting 'infinity' in the ejabberd.yml file, it didn't print anything, but when setting a numeric value it did print it. I'll test some more.

**Comment by fiaxh** [comment]
Thanks for looking into this. In that case, this is actually not an ejabberd quirk, but the standard-compliant way of announcing that there is no file size limit. And with this change, Dino is now actually handling it :)

**Comment by eerielili** [comment]
> **if such a limitation exists**.

Ooooh nice catch

**Pull request merged**
