### PR TITLE
Replace xmpp uris with the name of the person if they're in your roster

### PR DESCRIPTION
**Pull request by earboxer**
This is especially useful for users of Cheogram/JMP.chat for group MMSs, so you can know who is talking to you without having to memorize their cell numbers.

before

after

### CODE REVIEW

**Comment by speedygonzales9** [comment]
Duplicate of PR #1212?

**Comment by earboxer** [comment]
Yeah, looks like it is. My version has fewer features: it just replaces the links in the message view, not in the list view, but it *does* have a settings toggle to enable/disable this feature.

So... looking forward to either of these being merged (but not both ;)

**Comment by speedygonzales9** [comment]
Are you planning to change how `xmpp:` links are displayed in a push notification if they are known? This would be nice to see.

**Comment by dilinger** [comment]
Could probably work together to merge the two PRs, but I'd like to hear from the Dino maintainers that they'd actually be interested in merging either of them first. (I'm the author of #1212 )

**Comment by fiaxh** [comment]
We do not think that it would be a good idea to just modify a message like this.

Someone might actually want to send `xmpp:user@example.com` as a URI. If the receiving client just replaces that text, it means that certain texts can't be sent anymore.

We generally aim to display messages as they were written by the sender, since the sender knows best what they want to say. If the receiving client just modifies the sender's text, that might break the original meaning. If the sender wants the receiving client to do something with the message, it should annotate the message stanza in a standardized way. We would consider supporting this if it was properly standardized.

**Pull request closed without merging**
