### PR TITLE
Add note about Noto

### PR DESCRIPTION
**Pull request by licaon-kter**

### CODE REVIEW

**Comment by jugendhacker** [comment]
On debian stable it seems to be impossible to get the color emojis working! But I have them in B/W

**Comment by stevenroose** [comment]
@fiaxh :)

**Comment by kousu** [comment]
Any idea how to get this workign on OS X (#529)? I did installed from brew:

```
brew cask install homebrew/cask-fonts/font-noto-color-emoji
==> Tapping homebrew/cask-fonts
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts'...
remote: Enumerating objects: 1215, done.
remote: Counting objects: 100% (1215/1215), done.
remote: Compressing objects: 100% (465/465), done.
remote: Total 1215 (delta 798), reused 932 (delta 745), pack-reused 0
Receiving objects: 100% (1215/1215), 232.47 KiB | 6.12 MiB/s, done.
Resolving deltas: 100% (798/798), done.
Tapped 1182 casks (1,231 files, 1.1MB).
==> Satisfying dependencies
==> Downloading https://noto-website-2.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip
######################################################################## 100.0%
==> No SHA-256 checksum defined for Cask 'font-noto-color-emoji', skipping verification.
==> Installing Cask font-noto-color-emoji
==> Moving Font 'NotoColorEmoji.ttf' to '/Users/kousu/Library/Fonts/NotoColorEmoji.ttf'.
🍺  font-noto-color-emoji was successfully installed!
```

but emojis are still missing. They are shown as white (i.e. invisible) boxes. Do I need to recompile dino for it to pick them up?

**Comment by fiaxh** [comment]
The README now links to a [wiki page](https://github.com/dino/dino/wiki/Build) which lists dependencies. I added `Emoji font` to the list.

**Pull request closed without merging**
