### PR TITLE
Reject non-TLS URLs in HTTP File Upload

### LINKED ISSUE #697: OMEMO file transfer: won't send correct URI
I use my own XMPP server, which does not accept https connections to retrieve uploaded files, but it does accepts http connections on port 5280.

When sending a file with OMEMO enabled, dino sends incorrect aesgcm URIs. As a result, other clients cannot retrieve the file content. Instead of the correct URI "aesgcm://hostname.tld/foobar#", dino send "aesgcm://ostname.tld/foobar#" (the first letter of the hostname is missing).

The culprit might be in file dino/plugins/omemo/src/file_transfer/file_encryptor.vala, at the following line:
`aesgcm_link = "aesgcm://" + aesgcm_link.substring(8); // replace https:// by aesgcm://`

When I enable https connections (on port 5281), dino can send files using OMEMO, as expected.

### PR DESCRIPTION
**Pull request by linkmauve**
This is a MUST in the XEP.

Fixes #697.

### CODE REVIEW

**Comment by fiaxh** [comment]
Thanks for the PR. Your code didn't quite work because `.down_asci(5)` only returns the first 5 characters, however `http://` has 7, thus the check always evaluated to false. I fixed it in an additional commit :wink:

**Comment by SkewedZeppelin** [comment]
Eh, won't this break use of http:// .onions?

**Comment by fiaxh** [comment]
@SkewedZeppelin That's a good point, thanks for bringing it up. I think if .onion XMPP servers provide http:// URLs they'll run into various problems, especially with OMEMO encrypted file transfers, since they mandate https:// and a bunch of clients will likely not additionally try http://. Also, as @linkmauve mentioned, the XEP actually mandates https://. Thus, I think the .onion XMPP servers should actually provide https:// URLs, and use a self-signed certificate. This would be similar to how we handle connections to XMPP servers themselves - we require SSL but allow self-signed certificates for .onion servers (#958).
Do you know of .onion XMPP servers that hand out http:// URLs?

However, this brings up a different point: We should allow self-signed certificates for https:// .onion URLs. I opened an issue for that: #1149

**Comment by SkewedZeppelin** [comment]
@fiaxh 
I don't know of any public ones. I briefly ran one on a Pi years ago for testing a Briar like experience, but there were other issues at the time.
Now that I think about it, I think I still did have a self signed certificate on top.

**Pull request merged**
