### PR TITLE
Add spell-checking using Gspell

### PR DESCRIPTION
**Pull request by ThibG**

### CODE REVIEW

**Comment by ThibG** [comment]
While this PR works pretty well, it would be better to keep the spell-checking settings to a conversation, but I'm not sure how to do that yet.
Indeed, I think it is a very common use case to have different conversations in different languages, and the spell-checking settings should not have to be changed each time one changes conversations.

**Comment by ThibG** [comment]
Refactored a bit and made it so that conversations “remember” the language used for spell-checking (within a single execution of Dino… maybe it should be stored in the database, I don't know)

**Comment by Sylvhem** [comment]
I tried this feature and it works just fine. You can see examples of the spellchecking in action in the screenshots below. Being able to choose a different language on a per chatroom basis is a really nice touch.

Contextual menu listing multiple French words.
Contextual menu listing the available languages.

My only suggestion for improving this would be to use a twisting line (like it's usually the case for spellchecking) instead of a straight line. But frankly, this can be fixed in a later pull request.

**Comment by mimi89999** [comment]
@ThibG Could you please rebase on latest master? Actually, why this PR can't be merged?

**Comment by ThibG** [comment]
@mimi89999 rebased

**Comment by mimi89999** [comment]
Works well. Thanks a lot @ThibG. I hope that it will get merged one day...

**Comment by tetraf** [comment]
Works for me too. Very useful. Thanks @ThibG.

**Comment by mimi89999** [comment]
@mar-v-in Could you please review this PR? I think that it is a very important feature.

**Comment by mar-v-in** [comment]
Sorry @ThibG, @mimi89999 I thought I had replied here long ago, but apparently I didn't.
The only thing missing for me is what @ThibG already proposed: to store the conversation spell checker language in the database. I also think it might be worth considering adding an option to turn spell checking off for a conversation (and/or globally) for users that don't have a dictionary in the relevant language installed (in which case it would basically complain all the time).

I don't think we'll be able to merge this before 0.2 though, as we already decided to freeze features for the next release.

**Comment by fiaxh** [comment]
Thanks for your work and sorry it took so long to get it merged. It's merged now (830eba3a06506fd5ac527a74c8ce4ad5ba39cbf0, 0d3070643884b0a8d960058d1df4d6cd07f9ec84). I also made a setting for spell checking and persisted the chosen language (f12fc371a3bd00ac8c3183099d9d54528ef46bf0).

**Pull request closed without merging**
