### PR TITLE
Added previews

### PR DESCRIPTION
**Pull request by sojuz151**
Added support for generating previews for received links, including using the open graph protocol. 
Screenshot_20210704_135723

### CODE REVIEW

**Comment by ericschdt** [comment]
IMHO privacy and security wise it would be better if the sender generated the previews (on demand). Do you also check the file size somewhere before downloading any image?

**Comment by licaon-kter** [comment]
@ericschdt so the sender can lie? Not sure if serious

**Comment by fiaxh** [comment]
Thanks for your PR.

I agree with @ericschdt. Previews should be generated by the sender and attached to the message. Automatically sending requests to arbitrary URLs leaks the users IP to that service and might even cause legal issues for the user depending on the content of the website and the jurisdiction the user is under.

>  so the sender can lie?

- Even with receiver-generated previews it is well possible to generate misleading previews. The server can serve different site contents depending on whether the request comes from a browser or another program/library. That way, the preview will suggest another content than what the user will see in the browser afterwards.
- The sender of a link can already lie about the contents. For example by sending a normal message with a claim about the link content. Or by sending a link that looks like a trustworthy website on first glance.

**Comment by sojuz151** [comment]
> IMHO privacy and security wise it would be better if the sender generated the previews (on demand). Do you also check the file size somewhere before downloading any image?

I added size checking in the new commit.

>Automatically sending requests to arbitrary URLs leaks the users IP to that service and might even cause legal issues for the user depending on the content of the website and the jurisdiction the user is under.

The default behaviour is to just show a "Download Preview" button without making any network request. Users can enable automatic previews in the setting.

**Comment by fiaxh** [comment]
> The default behaviour is to just show a "Download Preview" button without making any network request. Users can enable automatic previews in the setting.

> Privacy issues aside (just disable it by default...)

That feels like we'd be providing the user with the choice "You can have EITHER privacy OR a good UX". However, combining a good UX with privacy-friendly technology is exactly what Dino is about :slightly_smiling_face: I think that previews are a relevant feature, but I don't see us merging a preview feature in which the receiving client requests the URL.

Unfortunately, XMPP currently does not provide a good solution for previews. In my opinion, the best approach would be to have the sending client generate a preview and send it along with the message. The format of the sent preview should be standardized in a XEP such that any client can implement it.

**Comment by cthu1hoo** [comment]
If we look back on how other XEPs like MAM (written, what, 10 years ago?) are being implemented, I think it's rather more likely that I would grow old and die before this hypothetical preview XEP you're describing would gain any sort of client adoption.

I suppose Gajim continues to be the only game in town until XMPP ecosystem dies out entirely. :shrug:

**Comment by licaon-kter** [comment]
@cthu1hoo why the drama?

Wasn't this an usecase for https://xmpp.org/extensions/xep-0385.html ?

Others are doing this: https://www.mysk.blog/2020/10/25/link-previews/ 

So which of those solutions you feel is nicer?

**Pull request closed without merging**
