### PR TITLE
Added luxembourgish translation

### PR DESCRIPTION
**Pull request by the-metalgamer**

### CODE REVIEW

**Comment by d9h20f** [comment]
You already added this translation via Weblate, why make a pull request on top?

**Comment by the-metalgamer** [comment]
To also include the translations for the plugins as they are not yet on weblate afaik

**Comment by fiaxh** [comment]
Thanks for also translating the plugins! Could you please remove main/po/* from this PR to not introduce conflicts with weblate? I will then merge your "main" translations from weblate.

**Comment by the-metalgamer** [comment]
Done

**Pull request merged**
