### PR TITLE
Use libsecret to store the password

### LINKED ISSUE #102: Save passwords in keyring
By default, all passwords should be saved in the available keyring (gnome-keyring).

### PR DESCRIPTION
**Pull request by linkmauve**
Also migrate the old plain-text password to the libsecret store, and replace it with an empty string to avoid keeping it in plain text.

Fixes #102.

### CODE REVIEW

**Comment by linkmauve** [comment]
So there are a bunch of issues with this patch:
- If the user doesn’t have DBus support (the case on Windows apparently), libsecret won’t be able to communicate with a SecretService, rendering storage of the password ineffective, and won’t connect automatically without any error message being given to the user.
- If the user doesn’t have a SecretService installed, same behaviour as previously.
- If the user didn’t start their SecretService, libsecret will block Dino while DBus starts it automatically, waits for the keyring to be unlocked, and then give back the password.

It seems pretty bad to me to simply fallback to storing the password in plain text in any of the first two cases, some of which could be caused by an attacker trying exactly to get access to the plain text password. It also seems pretty annoying to ask the user for their password repeatedly at each connection if it couldn’t be retrieved securely by libsecret. If anyone has a better idea, let me know!

**Comment by NicoHood** [comment]
I think the best solution is to make libsecret a required dependency. Does dino even provide windows builds? Is this the aim? Maybe you can abstract this layer and use a different mechanism on windows. This way it is always 100% secure (no fallback) on linux, and insecure on windows (which shouldnt matter for the 0815 windows user at all).

**Comment by RalfJung** [comment]
> fallback to storing the password in plain text in any of the first two cases

Please don't. Passwords should not be stored in clear text. At the very least, the application should yell loudly before doing so.

**Comment by RalfJung** [comment]
I merged this patch into the dino I use locally and I can confirm that it works just fine :)  Thanks!

**Comment by linkmauve** [comment]
#254 took over this PR, closing.

**Pull request closed without merging**
