### PR TITLE
Add '--version' flag

### PR DESCRIPTION
**Pull request by sshikaree**
#852

### CODE REVIEW

**Comment by licaon-kter** [comment]
The Occupant change is for what?

**Comment by sshikaree** [comment]
@licaon-kter 
> The Occupant change is for what?
No, it's not specifically for that.

**Comment by sshikaree** [comment]
@licaon-kter 
Sorry, I misread your question) The Occupant change fixes #1013. One of them.

**Comment by licaon-kter** [comment]
Better have that as a separate PR

**Comment by sshikaree** [comment]
OK, removed that commit.

**Comment by fiaxh** [comment]
Thanks! Feel free to also PR your other commit.

**Pull request merged**
